// بيانات واجهة اصطناعية صريحة. لا تُحفظ في SQLite ولا تُعامل كنتائج اعتماد حقيقية.
export const demoTenders = [
  {
    id: "DEMO-001",
    title: "مثال تجريبي — صيانة مبنى خدمي",
    agency: "جهة تجريبية",
    reference: "DEMO-001",
    fee: 0,
    region: "منطقة القصيم",
    deadline: "2026-09-15 09:59",
    status: "جديدة",
    documents: "لم تُفتح",
    score: 82,
    platformStatus: "المنافسات النشطة (تقديم العروض)",
    activity: "المقاولات",
    tenderType: "شراء مباشر",
    publishedAt: "2026-08-13",
    contractDuration: "90 يوم",
    guarantee: "لا يوجد ضمان",
  },
  {
    id: "DEMO-002",
    title: "مثال تجريبي — ترميم وتأهيل مرفق حكومي",
    agency: "جهة تجريبية",
    reference: "DEMO-002",
    fee: 500,
    region: "المنطقة الشرقية",
    deadline: "2026-09-22 09:59",
    status: "قيد المراجعة",
    documents: "الكراسة",
    score: 74,
    platformStatus: "المنافسات النشطة (تقديم العروض)",
    activity: "المقاولات",
    subActivity: "مقاولات عامة للمباني (الإنشاء، الإصلاح، الهدم، الترميم)",
    tenderType: "منافسة عامة",
    publishedAt: "2026-08-13",
    contractDuration: "180 يوم",
    guarantee: "ضمان ابتدائي",
    quantitySummary: "بنود تجريبية لأعمال مدنية وكهربائية",
    remoteAttachments: ["مثال-كراسة-الشروط.pdf", "مثال-جدول-الكميات.xlsx"],
  },
  {
    id: "DEMO-003",
    title: "مثال تجريبي — إنشاء مظلات ومواقف سيارات",
    agency: "جهة تجريبية",
    reference: "DEMO-003",
    fee: 600,
    region: "منطقة الرياض",
    deadline: "2026-10-01 09:59",
    status: "مناسبة",
    documents: "الكراسة + الكميات",
    score: 88,
    platformStatus: "المنافسات النشطة (تقديم العروض)",
    activity: "المقاولات",
    tenderType: "منافسة عامة",
    publishedAt: "2026-08-13",
    contractDuration: "120 يوم",
    guarantee: "ضمان ابتدائي",
  },
] as const;
